# 値の評価と表示
- 値の評価とは、入力した値を評価してその結果を返すこと
  - `1 + 1`という式を評価したら 2 という結果を返す
  - `bookTitle` という変数を評価したら、変数に代入されている値を返す
  - `const x = 1;`という文を評価することで変数を定義するが、この文には返り値はない

## コードの評価とエラー
### 構文エラー
- 構文エラーは書かれたコードの文法が間違っている場合に発生するエラー
  - JavaScriptエンジンは、コードをパース（解釈）してから、プログラムとして実行できる形に変換して実行する
  - コードをパースする際に文法の問題が見つかると、その時点で構文エラーが発生するためプログラムとして実行できない
  ```JavaScript
  // 関数呼び出しに)をつけ忘れているため構文エラーが発生する
  console.log(1; // => SyntaxError: missing ) after argument list
  ```
  ```JavaScript
  // 関数呼び出しに)をつけ忘れているため構文エラーが発生する
  SyntaxError: missing ) after argument list[詳細] index.js:1:13
  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      ^^^^^^^^　^^^^
  エラーの種類                |                        | 　行番号:列番号
                  エラー内容の説明                 ファイル名
  ```

### エラーメッセージ
```JavaScript
cosnt a = 1; // constをcosntとタイプミスしている
```
| **メッセージ** | **意味** |
| ---- | ---- |
| `SyntaxError: unexpected token: identifier` | エラーの種類は`SyntaxError`で、予期しない識別子(変数名 `a`)が指定されている|
| index.js:1:6 | 例外がindex.jsの1行目6列目で発生したこと |
- 1行目6列目(行は1から、列は0からカウントする)であるaという文字列がおかしいという意味
  - 実際には`cosnt`というタイプミスがこの構文エラーの原因
  - エラーメッセージとエラーの原因は必ずしも一致しない

### 実行時エラー
- 実行時エラーはプログラムを実行している最中に発生するエラー(ランタイムエラーとも呼ばれる)
  - 実行時エラーが発生した場合は、そのコードは構文としては正しいが、別のことが原因でエラーが発生している
  ```JavaScript
  // xという存在しない変数を参照したため、ReferenceErrorという実行時エラーが発生
  const value = "値";
  console.log(x); // => ReferenceError: x is not defined
  ```

### エラーメッセージ
```JavaScript
console.log(x); // ReferenceError: x is not defined[詳細] index.js:2:1
```
| **メッセージ** | **意味** |
| ---- | ---- |
| `ReferenceError: x is not defined` | エラーの種類は`ReferenceError`で、`x`という未定義の識別子を参照したため発生 |
| `index.js:2:1` | 例外が`index.js`の2行目1列目で発生したこと |
- `x`という変数や関数が存在するかは、実行してみないとわからないため、実行して`x`という識別子を参照したときに、初めて`x`が存在するかが判明し、`x`が存在しない場合は`ReferenceError`となる
- 実行時エラーは該当する箇所を実行するまで、エラーになるかがわからない場合も多いため、どこまで実行できたか順番に追っていくような、エラーの原因を特定する作業が必要になる(**デバッグ**と呼ぶ)

